### ISSUE TITLE
CCD reduction software does not discriminate different gratings

### ISSUE THREAD

**Issue by simontorres** [simontorres/goodman#28]
When processing multi-grating data the ccd reduction pipeline can not distinguish different grating/filters configuration for flat correction. Also flats are not normalized.

**Comment by simontorres** [comment]
Grating and filter discrimination solved. Need to check the flat normalization issue @b1quint

**Comment by b1quint** [comment]
What would be the Flat Normalization Issue? I tried to find it but I could not. Could you cite it, give me the link or explain a bit better?

**Comment by simontorres** [comment]
This is the "intensity profile" of the flat image.
![flat1](https://cloud.githubusercontent.com/assets/3878895/22473354/66097ade-e7b7-11e6-8b7e-bde08d8c6ef5.png)
![flat_column](https://cloud.githubusercontent.com/assets/3878895/22473357/6a14870e-e7b7-11e6-850c-0f38f22cb9fb.png)

**Comment by simontorres** [comment]
I meant "master flat".

**Comment by simontorres** [comment]
This issue is no longer valid since the updated version of the CCD Reduction pipeline
